# Generated by Django 3.1.1 on 2020-09-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputPath', models.CharField(max_length=200)),
                ('outputPath', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
